lsi: false
safe: true
source: eva-val/eva-va.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: tareqdandachi/jekyll-shell-theme
